name: CI lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          R -e 'install.packages("lintr")'

      - name: Run lintr
        run: |
          R -e 'library(lintr)
          lint_dir(
            linters = with_defaults(
              line_length_linter = line_length_linter(80),
              object_name_linter = object_name_linter(styles = c("snake_case", "camelCase")),
              assignment_linter = assignment_linter(),
              spaces_left_parentheses_linter = spaces_left_parentheses_linter()
            )
          )'
